### ISSUE TITLE
Need Wiki to be enabled to make discussion notes and share ideas

### ISSUE THREAD

**Issue by rpannu** [bhatia14/ttc_ml_delays#1]
I tried to create wiki page but I am not allowed to do so, can I be given wiki editor rights. You may create a starter page and let us see how we can use it.
DA aka RP

**Comment by bhatia14** [comment]
I created one https://github.com/bhatia14/ttc_ml_delays/wiki

**Comment by bhatia14** [comment]
@dsavatar  you need to accept the collaborator request for github repo, for accessing/changing repo.
